export const posts = [
  {
    key: "1",
    id: "post123",
    user: "johndoe",
    caption: "Beautiful sunset at the beach #sunset #beach",
    likes: 1250,
    comments: 42,
    status: "published",
    date: "2023-03-15",
    image: "/placeholder.svg?height=60&width=60",
  },
  {
    key: "2",
    id: "post456",
    user: "janedoe",
    caption: "My new artwork #art #creative",
    likes: 3420,
    comments: 128,
    status: "published",
    date: "2023-03-14",
    image: "/placeholder.svg?height=60&width=60",
  },
  {
    key: "3",
    id: "post789",
    user: "mikebrown",
    caption: "Hiking in the mountains #adventure",
    likes: 876,
    comments: 24,
    status: "flagged",
    date: "2023-03-13",
    image: "/placeholder.svg?height=60&width=60",
  },
  {
    key: "4",
    id: "post101",
    user: "sarahjones",
    caption: "My favorite coffee shop #coffee #morning",
    likes: 2100,
    comments: 56,
    status: "published",
    date: "2023-03-12",
    image: "/placeholder.svg?height=60&width=60",
  },
];
